version: '3.5'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379 # 將docker內的Redis的6379 port對應到實機6379 port
    volumes:
      - ./data:/data
    restart: always